### ISSUE TITLE
listes avec saut de ligne

### ISSUE THREAD

**Issue by newick** [clairezed/marges#5]
J'ai regardé vite fait et plusieurs solutions pour ne pas avoir le retour à la ligne dans certaines de tes listes à puces :

- ne pas avoir de ligne vide entre tes éléments de liste, markdown les interprète comme des paragraphes d'où le retour à la ligne :)
- mettre un truc du genre `li > p { display: inline; }`, comme ça ils se calent derrière la puce ;)

**Comment by clairezed** [comment]
Super, ta solution est absolument nickel ! Merci !
